server:
  port: 8081
  connection-timeout: 20000
management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: 'health,refresh,info'
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 10000
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 30

spring:
  application:
    name: minikube-internal-gateway